package view;

/**
 *
 * @author Daniel
 */
public class RegistroView extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public RegistroView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        lblDiaDelNino = new javax.swing.JLabel();
        lblDNI = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        lblEdad = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        lblTelPadre = new javax.swing.JLabel();
        txtTelPadre = new javax.swing.JTextField();
        txtNumRifa = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblComida = new javax.swing.JLabel();
        lblBebida = new javax.swing.JLabel();
        cmbBebida = new javax.swing.JComboBox<>();
        cmbComida = new javax.swing.JComboBox<>();
        btnGuardarRefrigerio = new javax.swing.JButton();
        lblNota = new javax.swing.JLabel();
        lblNumRifa = new javax.swing.JLabel();
        btnRifa = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        lblRegistrarBoy = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        BG.setBackground(new java.awt.Color(255, 255, 255));
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDiaDelNino.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        lblDiaDelNino.setForeground(new java.awt.Color(0, 0, 0));
        lblDiaDelNino.setText("Dia del niño");
        BG.add(lblDiaDelNino, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblDNI.setBackground(new java.awt.Color(0, 0, 0));
        lblDNI.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        lblDNI.setForeground(new java.awt.Color(0, 0, 0));
        lblDNI.setText("DNI");
        BG.add(lblDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        txtDNI.setBackground(new java.awt.Color(204, 204, 204));
        txtDNI.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        txtDNI.setForeground(new java.awt.Color(0, 0, 0));
        txtDNI.setBorder(null);
        BG.add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 170, 30));

        lblNombre.setBackground(new java.awt.Color(0, 0, 0));
        lblNombre.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre.setText("Nombres");
        BG.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txtNombre.setBackground(new java.awt.Color(204, 204, 204));
        txtNombre.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setBorder(null);
        BG.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 170, 30));

        txtApellido.setBackground(new java.awt.Color(204, 204, 204));
        txtApellido.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(0, 0, 0));
        txtApellido.setBorder(null);
        BG.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 170, 30));

        lblEdad.setBackground(new java.awt.Color(0, 0, 0));
        lblEdad.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        lblEdad.setForeground(new java.awt.Color(0, 0, 0));
        lblEdad.setText("Edad");
        BG.add(lblEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        txtEdad.setBackground(new java.awt.Color(204, 204, 204));
        txtEdad.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        txtEdad.setForeground(new java.awt.Color(0, 0, 0));
        txtEdad.setBorder(null);
        BG.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 70, 30));

        lblTelPadre.setBackground(new java.awt.Color(0, 0, 0));
        lblTelPadre.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        lblTelPadre.setForeground(new java.awt.Color(0, 0, 0));
        lblTelPadre.setText("Telefono del padre");
        BG.add(lblTelPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        txtTelPadre.setBackground(new java.awt.Color(204, 204, 204));
        txtTelPadre.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        txtTelPadre.setForeground(new java.awt.Color(0, 0, 0));
        txtTelPadre.setBorder(null);
        BG.add(txtTelPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 170, 30));

        txtNumRifa.setBackground(new java.awt.Color(204, 204, 204));
        txtNumRifa.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        txtNumRifa.setForeground(new java.awt.Color(0, 0, 0));
        txtNumRifa.setBorder(null);
        BG.add(txtNumRifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 70, 30));

        lblApellido.setBackground(new java.awt.Color(0, 0, 0));
        lblApellido.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        lblApellido.setForeground(new java.awt.Color(0, 0, 0));
        lblApellido.setText("Apellidos");
        BG.add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrar Refrigerio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto Light", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        lblComida.setBackground(new java.awt.Color(0, 0, 0));
        lblComida.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        lblComida.setForeground(new java.awt.Color(0, 0, 0));
        lblComida.setText("Comida");

        lblBebida.setBackground(new java.awt.Color(0, 0, 0));
        lblBebida.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        lblBebida.setForeground(new java.awt.Color(0, 0, 0));
        lblBebida.setText("Bebida");

        cmbBebida.setBackground(new java.awt.Color(204, 204, 204));
        cmbBebida.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        cmbBebida.setForeground(new java.awt.Color(0, 0, 0));
        cmbBebida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gaseosa", "Agua" }));

        cmbComida.setBackground(new java.awt.Color(204, 204, 204));
        cmbComida.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        cmbComida.setForeground(new java.awt.Color(0, 0, 0));
        cmbComida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perro Caliente", "Hamburguesa", "Papitas McDonald" }));

        btnGuardarRefrigerio.setBackground(new java.awt.Color(0, 0, 0));
        btnGuardarRefrigerio.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarRefrigerio.setText("Guardar refrigerio");
        btnGuardarRefrigerio.setBorder(null);
        btnGuardarRefrigerio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarRefrigerio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarRefrigerioActionPerformed(evt);
            }
        });

        lblNota.setBackground(new java.awt.Color(0, 0, 0));
        lblNota.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        lblNota.setForeground(new java.awt.Color(0, 0, 0));
        lblNota.setText("Nota: para registar el refrigerio introduce el DNI arriba");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBebida)
                    .addComponent(lblComida))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbComida, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNota, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 64, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardarRefrigerio, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComida)
                    .addComponent(cmbComida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBebida)
                    .addComponent(cmbBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(lblNota, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarRefrigerio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        BG.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 390, 180));

        lblNumRifa.setBackground(new java.awt.Color(0, 0, 0));
        lblNumRifa.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        lblNumRifa.setForeground(new java.awt.Color(0, 0, 0));
        lblNumRifa.setText("numRifa");
        BG.add(lblNumRifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        btnRifa.setBackground(new java.awt.Color(0, 0, 0));
        btnRifa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRifa.setForeground(new java.awt.Color(255, 255, 255));
        btnRifa.setText("Rifa");
        btnRifa.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btnRifa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRifa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRifaActionPerformed(evt);
            }
        });
        BG.add(btnRifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 70, 30));

        btnRegistrar.setBackground(new java.awt.Color(0, 0, 0));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        BG.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 70, 30));

        lblRegistrarBoy.setBackground(new java.awt.Color(0, 0, 0));
        lblRegistrarBoy.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        lblRegistrarBoy.setForeground(new java.awt.Color(0, 0, 0));
        lblRegistrarBoy.setText("Registrar niño");
        BG.add(lblRegistrarBoy, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarRefrigerioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarRefrigerioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarRefrigerioActionPerformed

    private void btnRifaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRifaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRifaActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel BG;
    public javax.swing.JButton btnGuardarRefrigerio;
    public javax.swing.JButton btnRegistrar;
    public javax.swing.JButton btnRifa;
    public javax.swing.JComboBox<String> cmbBebida;
    public javax.swing.JComboBox<String> cmbComida;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblBebida;
    private javax.swing.JLabel lblComida;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblDiaDelNino;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNota;
    private javax.swing.JLabel lblNumRifa;
    private javax.swing.JLabel lblRegistrarBoy;
    private javax.swing.JLabel lblTelPadre;
    public javax.swing.JTextField txtApellido;
    public javax.swing.JTextField txtDNI;
    public javax.swing.JTextField txtEdad;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtNumRifa;
    public javax.swing.JTextField txtTelPadre;
    // End of variables declaration//GEN-END:variables
}
